"""added username

Revision ID: 540dbb1067d3
Revises: 20b33aa898f3
Create Date: 2022-08-12 15:02:50.426717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540dbb1067d3'
down_revision = '20b33aa898f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
